server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producer_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    initialize-schema: always